### PR TITLE
Improve travis.yml

### PR DESCRIPTION
**Pull request by sergiy-petrov**
add php nightly version to tests (php8 at the moment) with allowing to fail

### CODE REVIEW

**Comment by fideloper** [comment]
hmmm any idea why this PR didn't appear to kick off a build? 👀

**Comment by fideloper** [comment]
Looks like it did but didn't set a link in GitHub perhaps: https://travis-ci.org/github/fideloper/TrustedProxy/jobs/740395754

**Comment by sergiy-petrov** [comment]
@fideloper hmm not sure how to resolve that issue with phpunit dependency version. Any advice?

**Comment by sergiy-petrov** [comment]
@fideloper I've simply added "^6.0|^9.3.3" for phpunit and seems it works

**Comment by fideloper** [comment]
Thanks! I'll take a look to see if there are different phpunit options for that as well (I wonder if version 7 or 8 should be used for older PHP versions).

**Comment by sergiy-petrov** [comment]
I've also removed odd "syntaxCheck" phpunit parameter

https://stackoverflow.com/questions/44328114/phpunit-what-does-syntaxcheck-configuration-parameter-stands-for-exactly

**Comment by sergiy-petrov** [comment]
@fideloper I've also added php 8.0 to travis tests since it's already released. 

Btw, seems travis tests got stuck (or are queueing very long time), have you considered moving to travis-ci.com/github actions instead? Seems they will shut down their travis-ci.org (not to be confused with travis-ci.com) servers - https://discourse.julialang.org/t/reminder-travis-ci-org-shuts-down-on-december-31-2020/47234

**Comment by fideloper** [comment]
Yep, that's true I should do that move! I'm hoping to soon.

**Comment by fideloper** [comment]
GitHub Actions in place, Travis removed.

Thanks!

**Pull request closed without merging**
