### PR TITLE
[2.0] Initial Laravel 5 Support

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by fideloper** [comment]
Looks like composer didn't like that: `Your requirements could not be resolved to an installable set of packages.`

**Comment by GrahamCampbell** [comment]
One sec...

**Comment by GrahamCampbell** [comment]
Does that work now I wonder?

**Comment by GrahamCampbell** [comment]
Hmm, your tests are passing, but they should have been broken by my change. I'll take a look...

**Comment by GrahamCampbell** [comment]
@fideloper Alright - I've rewritten the tests now. :)

**Comment by fideloper** [comment]
Let's give it a go! :D

**Pull request merged**
