### PR TITLE
Updated Deprecated Variables

### PR DESCRIPTION
**Pull request by lukepolo**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
This breaks support for earlier laravel versions though?

**Comment by lukepolo** [comment]
Probably , needs a new minor version ?

**Comment by fideloper** [comment]
I'm going to keep it the way it is now as until we're closer to needing to change it, in which case we may need to change documentation to tell users of it in older Laravel versions to use a specific version.

**Comment by fideloper** [comment]
These are also set to the updated version in Laravel 5.5's Middleware. Since this package will otherwise be used in older Laravel's, that might implicitly solve this.

**Pull request closed without merging**
