### PR TITLE
Use config_path() helper

### PR DESCRIPTION
**Pull request by barryvdh**
New helper goodies ;)

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
:+1:

**Comment by fideloper** [comment]
Thanks!

**Comment by fideloper** [comment]
whoops, except of course snappy.php is the wrong file :P -

I'll update that on my end.

**Comment by GrahamCampbell** [comment]
lol

**Comment by barryvdh** [comment]
Whoops, copy-paste to fast

**Comment by fideloper** [comment]
no problem! thanks for the PR!

**Pull request merged**
