### PR TITLE
Cleanup And Fixes

### PR DESCRIPTION
**Pull request by GrahamCampbell**
* Config should be dealt with in the boot method (people can override it in the register method first because in the boot method we're only setting config that doesn't exist yet - very important) - I checked this with Taylor 2 days ago
* I've dropped the dash from the config file - I think it just looks weird sitting next to the other config files
* I've PSR-2ed this thing
* I've removed a small amount of unneeded code

### CODE REVIEW

**Comment by fideloper** [comment]
thanks!

**Comment by GrahamCampbell** [comment]
@fideloper Is the v3.0.0 coming soon?

**Comment by fideloper** [comment]
YESSSSSSSSSS. Thanks for the reminder.

To my knowledge I need to update composer.json for v3 -

```json
"extra": {
        "branch-alias": {
            "dev-master": "2.0-dev"
        }
    }
```

And then create a 3.0.0 tag. 

Think I'm missing anything?

**Comment by GrahamCampbell** [comment]
I assumed you'd be merging develop to master, deleting the develop branch, then updating the branch alias to 3.0-dev and tagging.

**Comment by fideloper** [comment]
Yep, all that! And updating docs so it's not "beta" or w/e. I always forget the mechanics of proper tagging/packagist stuff :D
 
Thanks!

**Comment by GrahamCampbell** [comment]
NB, it doesn't really matter what the branch alias when you tag - packagist always just reads the latest one and ignores the rest, so if you ever forget to update it when tagging a release, it's not the end of the world. :)

**Comment by fideloper** [comment]
great, thanks!

**Pull request merged**
