### PR TITLE
Fixed crashing on old laravel

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by ConnorVG** [comment]
Did you have a stroke writing this code?

**Comment by GrahamCampbell** [comment]
:trollface:

**Comment by GrahamCampbell** [comment]
Ping @fideloper. :)

**Comment by fideloper** [comment]
Thanks, just got back from vacation yesterday, will check this out.

**Comment by GrahamCampbell** [comment]
👍

**Pull request merged**
