### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by matt-allan**
The docs mention a lot of things that no longer apply since the 4.0 release of this package.

- Update config examples.
- Remove docs about changing X-Forwarded-* header names as it's not longer supported*.
- Remove docs for deprecated `**` syntax.
- Update trusted header config to use bitmasks instead of an array.
- Add note about package auto-discovery.

* Symfony [now recommends](https://symfony.com/doc/current/deployment/proxies.html#custom-headers-when-using-a-reverse-proxy) editing `public/index.php` to accomplish this but I'm not sure if that's the best solution for Laravel. It may be possible to hook into a framework event instead to do this in Laravel.

### CODE REVIEW

**Comment by fideloper** [comment]
Some people use older versions of Laravel, which in turn pull in the older versions of Symfony.

(Altho the reader file could certainly be cleaned up!)

**Comment by matt-allan** [comment]
Hey @fideloper,

I understand your point that users may be using older versions of the package. What do you think about updating the README in the master branch to reflect the latest version of the package and linking to previous tags, i.e. [this link for 3.0](https://github.com/fideloper/TrustedProxy/tree/3.0.0)? I was personally really confused when I checked the README and the majority of the examples did not work.

**Comment by fideloper** [comment]
(Sorry I didn't mean to close it in a way that meant "this is rejected" - it's just hard to communicate while juggling work and kids at home , so I made a quick note)

I do like that idea - I'm not sure the best way to do it. Have a different readme.md file per tag? (and backfill/update the tags with that commit with an updated readme?)

**Comment by matt-allan** [comment]
Hey,

No worries, thanks for communicating that. I don't think you would necessarily need a different readme file per tag or to backfill the readmes. Assuming the readme was correct at the time the tag was made you could link to the version of the readme when that tag was made, i.e.

> You can still use this package for Version 4 of Laravel. [See the latest v2 tag of this repository](https://github.com/fideloper/TrustedProxy/tree/2.1.1), which is compatible with version 4 of Laravel.

If for some reason an older version's README needed to be updated it could be updated the same way a bugfix would be released for an older version - checkout the latest 2.* tag, create a branch, merge, and create a new 2.* tag.

**Comment by fideloper** [comment]
Ah, good point. I know there's been a mix of stuff since version 5.5 or so, it may still not be as clean, but that's likely better than nothing!

**Pull request closed without merging**
